language: python
matrix:
    include:
        - python: 2.7  # these are just to make travis's UI a bit prettier
          env: TOX_ENV=py27
        - python: 2.6
          env: TOX_ENV=py26
        - python: 2.7
          env: TOXENV=cy27
        - python: 2.6
          env: TOX_ENV=cy26

install: "pip install tox coveralls --use-mirrors"
script:
  - "rm -Rf .tox"
  - tox
