language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
#install: "pip install -r requirements.txt"
install: "pip install tox coveralls --use-mirrors"
# command to run tests
script: tox
